name: Deploy pipelines

on: 
  workflow_dispatch:
    inputs:
      directory:
        description: Directory of the pipeline
        required: true
      message:
        description: Commit message
        required: false


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Setup openhexa
        uses: blsq/openhexa-cli-action@1.0.3
        with:
          workspace: ${{ vars.WORKSPACE }}
          token: ${{ secrets.OH_TOKEN }}
          openhexa_version: settings
      - name: Deploy pipeline
        run: |
          openhexa pipelines push ${{ github.event.inputs.directory }} 
        

